use_frameworks!
platform :ios, '8.0'

target 'JKServiceManager_Example' do
  pod 'JKServiceManager', :path => '../'

  target 'JKServiceManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end

